name: fl_example
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_curiosity: ^3.5.0
  flutter_waya: ^1.18.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_flavorizr: ^2.1.0

flutter:
  uses-material-design: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
  flavors:
    apple:
      app:
        name: "Apple App"
      android:
        applicationId: "com.fl.example.apple"
      ios:
        bundleId: "rex.xichangfabu"
    banana:
      app:
        name: "Banana App"
      android:
        applicationId: "com.fl.example.banana"
      ios:
        bundleId: "rex.xichangfabu"

fl_flavors:
  android:
    main:
      target: lin/main.dart
    bate:
      target: lin/main_beta.dart
  ios:
    main:
      target: lin/main.dart
